import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Parthasarathi Gayen</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>

      <h1>This is Book page</h1>
    </>
  )
}
